### ISSUE TITLE
"Initial test contains 15 boths" message when running picire in --atom=both mode

### ISSUE THREAD

**Issue by DRMacIver** [renatahodovan/picire#16]
As per title: If you use the `--atom=both` flag then the initial message about the test case size says that the file contains (say) 15 "boths". This is presumably the line count (at least, the numbers agree), so it should say 15 lines.

It correctly reports "characters" rather than "boths" for the second run when it minimizes by character.

(I apologise for how incredibly nitpicky this issue is)

**Comment by renatahodovan** [comment]
Indeed, thanks for the report. Any further nitpicky feedback is welcome :)
